### ISSUE TITLE
Potential Typo?

### ISSUE THREAD

**Issue by abhi-glitchhg** [dlsyscourse/hw0#3]
![image](https://user-images.githubusercontent.com/72816663/189976073-771946e7-91da-471c-8ba4-c72f18a0f072.png)

I think there is a typo here;  Summation sign should be there in the denominator. 

Btw this is in 4th question of the notebook.

**Comment by ashertrockman** [comment]
The summation happens via outer product with the all-ones row vector ($1^T$).

**Comment by abhi-glitchhg** [comment]
Ohh, i was not aware about this notion of representing all ones as this. Confused because of transpose operator on scalar, now it makes sense. 


thanks 👍
